import type { Level, LevelTier } from "./types";

/**
 * The authoritative curriculum. SPEC.md section 7.
 *
 * All 20 levels carry full `topics` arrays from Phase 1 so the whole route is
 * legible from day one, even where lessons are still planned. `status` says
 * whether lessons exist yet — it is never used to hide a level from the map.
 */
export const curriculum: Level[] = [
  /* ---------------- Foundations ---------------- */
  {
    number: 1,
    slug: "cnc-overview",
    title: "CNC overview",
    summary:
      "What a CNC machine actually is, what the common types do, and how a drawing on a screen becomes a metal part.",
    tier: "foundation",
    lessonSlugs: ["what-is-a-cnc-machine", "cad-to-finished-component"],
    requires: [],
    topics: [
      "What the letters CNC stand for and what each part means",
      "Manual machining versus numerically controlled machining",
      "The five subsystems every CNC machine has",
      "Mills, lathes, routers, grinders and machining centres",
      "Vertical and horizontal machining centres compared",
      "The CAD → CAM → post-processor → G-code → machine chain",
      "Who does what: designer, programmer, setter, operator",
      "Where accuracy actually comes from",
      "What a machine cannot do, and why fixtures exist",
    ],
    status: "published",
  },
  {
    number: 2,
    slug: "how-movement-works",
    title: "How movement works",
    summary:
      "Coordinates, axes and offsets — how the control knows where the tool is and how it moves it there.",
    tier: "foundation",
    lessonSlugs: ["understanding-xyz", "how-a-ball-screw-moves-an-axis"],
    requires: [1],
    topics: [
      "The right-hand rule and the standard X, Y, Z convention",
      "Why axis direction is defined by tool motion relative to the workpiece",
      "Rotary axes A, B and C",
      "Machine coordinate system versus work coordinate system",
      "Work offsets, tool length offsets and cutter compensation",
      "Absolute and incremental positioning",
      "Linear and circular interpolation",
      "Turning rotary motor motion into linear axis motion",
      "Ball screws, lead screws, rack and pinion, linear motors",
      "Guideways: profile rails, box ways and their trade-offs",
      "Backlash, preload and stiffness in a feed drive",
    ],
    status: "published",
  },
  {
    number: 3,
    slug: "cutting-fundamentals",
    title: "Cutting and machining fundamentals",
    summary:
      "What happens where the tool meets the metal: chips, forces, heat and why tools wear out.",
    tier: "foundation",
    lessonSlugs: [],
    requires: [1, 2],
    topics: [
      "Cutting speed, feed per tooth and depth of cut defined",
      "How a chip actually forms: shear zone, rake face, built-up edge",
      "Chip thinning and why radial engagement changes the sums",
      "Cutting force components and where they push the machine",
      "Specific cutting force and its role in power estimates",
      "Heat generation and where the heat goes",
      "Tool wear mechanisms: flank wear, crater wear, chipping",
      "Tool materials: HSS, carbide, coatings, ceramics",
      "Machinability of steels, stainless, aluminium, cast iron and titanium",
      "Climb versus conventional milling",
      "Surface finish and what actually controls it",
      "Coolant and minimum-quantity lubrication",
    ],
    status: "planned",
  },

  /* ---------------- Mechanical design ---------------- */
  {
    number: 4,
    slug: "mechanical-machine-design",
    title: "Mechanical machine design",
    summary:
      "The structure that holds tool and workpiece apart: layouts, stiffness, damping and staying still when things get hot.",
    tier: "mechanical",
    lessonSlugs: ["intro-to-machine-architecture"],
    requires: [1, 2],
    topics: [
      "The structural loop and why its length matters",
      "C-frame, gantry, bridge, box-in-box and portal layouts",
      "Moving-table versus moving-gantry designs",
      "Static stiffness and where compliance hides",
      "Damping: material damping, joint damping, tuned dampers",
      "Cast iron, welded steel, polymer concrete and granite compared",
      "Ribbing, wall thickness and section design",
      "Thermal stability and symmetric design",
      "Chip and coolant management as a design input",
      "Design for assembly, alignment and scraping",
      "Finite element analysis: what it tells you and what it does not",
    ],
    status: "published",
  },
  {
    number: 5,
    slug: "linear-motion-axis-design",
    title: "Linear motion and axis design",
    summary:
      "Choosing and sizing the rails, screws and bearings that carry an axis, and the limits that catch people out.",
    tier: "mechanical",
    lessonSlugs: [],
    requires: [2, 4],
    topics: [
      "Profile rail guides: ball versus roller, preload classes",
      "Bearing block arrangements and moment loading",
      "Box ways, hydrostatic and hydrodynamic guideways",
      "Ball screw anatomy: nut recirculation, lead, accuracy grade",
      "Screw preload methods and the stiffness they buy",
      "Critical speed and why long screws whip",
      "Column buckling and fixed-fixed versus fixed-supported mounting",
      "Bearing selection for screw ends: angular contact pairs",
      "Direct drive and linear motors compared to screws",
      "Rack and pinion for long travels",
      "Life calculation basics and duty cycle",
      "Lubrication and sealing as service-life decisions",
    ],
    status: "planned",
  },
  {
    number: 6,
    slug: "spindle-systems",
    title: "Spindle systems",
    summary:
      "The rotating heart of the machine: what limits its speed, torque, power and stiffness.",
    tier: "mechanical",
    lessonSlugs: [],
    requires: [3, 4],
    topics: [
      "Belt-driven, direct-drive, integral motor and cartridge spindles",
      "Reading a torque and power curve properly",
      "Constant-torque and constant-power regions",
      "Spindle bearings: angular contact, preload, grease versus oil-air",
      "Bearing arrangement and its effect on nose stiffness",
      "Thermal growth and spindle chillers",
      "Tool interfaces: BT, CAT, HSK, Capto and their clamping principles",
      "Drawbar force, pull studs and taper contact",
      "Runout, balance grades and their effect on tool life",
      "Through-spindle coolant",
      "Spindle condition monitoring",
    ],
    status: "planned",
  },
  {
    number: 11,
    slug: "auxiliary-systems",
    title: "Pneumatics, hydraulics and auxiliary systems",
    summary:
      "Air, oil, coolant and swarf — the support systems that decide whether a machine can actually run a shift.",
    tier: "mechanical",
    lessonSlugs: [],
    requires: [4],
    topics: [
      "What pneumatics are good at and what they are not",
      "Air preparation: filtration, regulation, lubrication, drying",
      "Cylinders, valves and the basics of circuit reading",
      "Hydraulic power units, accumulators and counterbalance circuits",
      "Where hydraulics still win: clamping force and vertical axis balance",
      "Coolant systems: pumps, filtration, concentration, management",
      "Through-spindle coolant pressure and filtration requirements",
      "Chip conveyors, augers and chip breaking",
      "Centralised lubrication systems and metering units",
      "Mist extraction and enclosure ventilation",
      "Why auxiliary systems dominate maintenance workload",
    ],
    status: "planned",
  },
  {
    number: 12,
    slug: "tool-changing-workholding",
    title: "Tool changing and workholding",
    summary:
      "Getting the right tool into the spindle and the workpiece to stay exactly where you put it.",
    tier: "mechanical",
    lessonSlugs: [],
    requires: [4, 6],
    topics: [
      "Carousel, umbrella and chain tool magazines",
      "Twin-arm changers and chip-to-chip time",
      "Tool identification, tool tables and life management",
      "Tool presetting and offset entry",
      "Vices, chucks, collets and their gripping principles",
      "Clamping force versus cutting force: the sums that matter",
      "Locating principles: 3-2-1, datum surfaces, over-constraint",
      "Modular and zero-point systems",
      "Vacuum, magnetic and adhesive workholding",
      "Fixture design for repeatability and for chip clearance",
      "Pallet changers and how they buy spindle time",
    ],
    status: "planned",
  },

  /* ---------------- Drives and control ---------------- */
  {
    number: 7,
    slug: "motors-servos-motion-control",
    title: "Motors, servos and motion control",
    summary:
      "How an electrical command becomes a precisely controlled movement, and what a servo loop is really doing.",
    tier: "control",
    lessonSlugs: [],
    requires: [2, 5],
    topics: [
      "Stepper, brushed DC, brushless DC and AC servo motors compared",
      "Open loop versus closed loop control",
      "The cascaded position, velocity and current loops",
      "Encoders: incremental, absolute, rotary, linear",
      "Resolution, accuracy and the difference between them",
      "Feedforward, following error and gain tuning",
      "Inertia matching and why it dominates sizing",
      "Torque, continuous rating, peak rating and duty cycle",
      "Regeneration, braking resistors and DC bus behaviour",
      "Direct-drive rotary tables and torque motors",
      "Motor sizing workflow end to end",
    ],
    status: "planned",
  },
  {
    number: 8,
    slug: "electrical-machine-design",
    title: "Electrical machine design",
    summary:
      "Power, control voltages, cabinets and cabling — the architecture that makes the machine electrically sound.",
    tier: "control",
    lessonSlugs: [],
    requires: [7],
    topics: [
      "Supply arrangements, transformers and earthing concepts",
      "Main disconnect, protective devices and short-circuit thinking",
      "Control voltages and the reason 24 V DC dominates",
      "Cabinet layout, segregation and thermal management",
      "Drive and motor cabling, shielding and EMC practice",
      "Signal types: digital, analogue, encoder, fieldbus",
      "Industrial networks: EtherCAT, PROFINET, EtherNet/IP in outline",
      "I/O architecture and remote I/O",
      "Safety-related circuits as a separate architecture",
      "Documentation: schematics, terminal plans, cable schedules",
      "Why this work is reserved for qualified personnel",
    ],
    status: "planned",
  },
  {
    number: 9,
    slug: "cnc-control-software",
    title: "CNC control and software",
    summary:
      "What happens inside the control between reading a line of code and moving an axis.",
    tier: "control",
    lessonSlugs: [],
    requires: [7, 8],
    topics: [
      "Anatomy of a CNC control: HMI, interpreter, interpolator, PLC",
      "The look-ahead buffer and why it exists",
      "Trajectory planning, jerk limiting and corner behaviour",
      "Path tolerance and smoothing settings",
      "The integrated PLC and machine logic",
      "Parameters, machine data and what changing them risks",
      "Compensation tables: pitch error, backlash, volumetric",
      "Probing cycles and in-process measurement",
      "Adaptive control and load monitoring",
      "Networking, DNC and file management",
      "Simulation, verification and collision checking",
    ],
    status: "planned",
  },
  {
    number: 10,
    slug: "gcode-and-programming",
    title: "G-code and programming",
    summary:
      "Reading and writing the language the machine actually executes, one line at a time.",
    tier: "control",
    lessonSlugs: [],
    requires: [2, 9],
    topics: [
      "Program structure: blocks, words, addresses, comments",
      "G-codes and M-codes: motion versus machine function",
      "Rapid, linear and circular moves",
      "Absolute and incremental modes",
      "Work offsets and tool offsets in code",
      "Feed and speed commands, and constant surface speed",
      "Canned cycles for drilling and tapping",
      "Cutter radius compensation in practice",
      "Subprograms, macros and parametric programming",
      "Common beginner mistakes and how they crash machines",
      "Reading a post-processed CAM program critically",
    ],
    status: "planned",
  },

  /* ---------------- Proving and building ---------------- */
  {
    number: 13,
    slug: "accuracy-geometry-metrology",
    title: "Accuracy, geometry and metrology",
    summary:
      "What accuracy, repeatability and resolution really mean, and how machine geometry is measured and proven.",
    tier: "practice",
    lessonSlugs: ["accuracy-repeatability-resolution"],
    requires: [2, 4],
    topics: [
      "Accuracy, repeatability and resolution as three separate ideas",
      "Systematic error versus random error",
      "Positioning accuracy along an axis",
      "Geometric errors: straightness, squareness, parallelism, angular errors",
      "The 21 error components of a three-axis machine",
      "Volumetric accuracy and error budgets",
      "Instruments: dial indicators, test bars, granite squares, levels",
      "Laser interferometry and what it measures",
      "Ballbar testing and reading its plot",
      "Circular and contouring tests as diagnostics",
      "The purpose and scope of ISO 230 and ISO 10791 (consult the standards for requirements)",
      "Measurement uncertainty and environmental control",
    ],
    status: "published",
  },
  {
    number: 14,
    slug: "thermal-behaviour",
    title: "Thermal behaviour",
    summary:
      "Why a machine that was accurate at 8am is not at 2pm, and what designers do about it.",
    tier: "practice",
    lessonSlugs: [],
    requires: [4, 13],
    topics: [
      "Heat sources: spindle, drives, screws, cutting, ambient",
      "Thermal expansion and the coefficients that matter",
      "Thermal drift of the structural loop",
      "Warm-up cycles and why they are specified",
      "Symmetric design and thermally stable materials",
      "Cooling: spindle chillers, screw cooling, cabinet cooling",
      "Thermal compensation models in the control",
      "Environmental control of the machine shop",
      "Measuring thermal drift over a shift",
      "Designing a test that separates thermal from geometric error",
    ],
    status: "planned",
  },
  {
    number: 15,
    slug: "vibration-machine-dynamics",
    title: "Vibration and machine dynamics",
    summary:
      "Chatter, resonance and dynamic stiffness — why the same tool cuts beautifully at one speed and screams at another.",
    tier: "practice",
    lessonSlugs: [],
    requires: [4, 6],
    topics: [
      "Free, forced and self-excited vibration",
      "Natural frequency, mode shapes and damping ratio",
      "Dynamic stiffness versus static stiffness",
      "Regenerative chatter explained from first principles",
      "Stability lobe diagrams and how to use them",
      "Tap testing and frequency response measurement",
      "Tool overhang as the usual culprit",
      "Spindle speed selection to avoid chatter",
      "Variable helix and variable pitch tooling",
      "Structural damping treatments and tuned mass dampers",
      "Foundations, isolators and floor coupling",
    ],
    status: "planned",
  },
  {
    number: 16,
    slug: "machine-safety-compliance",
    title: "Machine safety and compliance",
    summary:
      "How a machine is made safe by design, and the framework of standards and duties that surrounds it.",
    tier: "practice",
    lessonSlugs: [],
    requires: [4, 8],
    topics: [
      "Hazard identification and risk assessment as a process",
      "The hierarchy of risk reduction",
      "Guarding, interlocks and enclosure design principles",
      "Emergency stop as a complement to, not a substitute for, safe design",
      "Safe speed, safe standstill and safe door-unlocking concepts",
      "Safety-related control systems in outline",
      "The purpose and scope of ISO 12100, ISO 13849-1, IEC 60204-1 and ISO 16090-1",
      "Why exact requirements must come from the standards themselves",
      "Verification, validation and the technical file",
      "Residual risk, instructions and training",
      "Regional legal frameworks and why they differ",
    ],
    status: "planned",
  },
  {
    number: 17,
    slug: "manufacturing-assembly",
    title: "Manufacturing and assembly",
    summary:
      "Turning a machine design into real parts and putting them together so the geometry is actually achieved.",
    tier: "practice",
    lessonSlugs: [],
    requires: [4, 5],
    topics: [
      "Casting, welding and stress relief of large structures",
      "Machining sequence for large frames",
      "Tolerance stack-up and what to control tightly",
      "Datum strategy across a multi-part structure",
      "Hand scraping, and why it survives in the era of CNC",
      "Rail mounting, alignment and reference edges",
      "Screw alignment and avoiding induced loads",
      "Fastening, doweling and joint stiffness",
      "Sub-assembly testing before final assembly",
      "Assembly documentation and traceability",
    ],
    status: "planned",
  },
  {
    number: 18,
    slug: "commissioning-validation",
    title: "Commissioning and validation",
    summary:
      "Proving that the machine you built does what the design said it would.",
    tier: "practice",
    lessonSlugs: [],
    requires: [13, 16],
    topics: [
      "Installation, levelling and foundation checks",
      "First power-up sequence and pre-checks",
      "Axis parameter setting, limits and homing",
      "Servo tuning and following-error checks",
      "Geometric alignment measurement and correction",
      "Positioning accuracy measurement and compensation entry",
      "Circular and contouring test acceptance",
      "Test-piece machining as functional proof",
      "Safety function verification",
      "Documentation handover and acceptance records",
      "The difference between acceptance testing and periodic verification",
    ],
    status: "planned",
  },
  {
    number: 19,
    slug: "maintenance-troubleshooting",
    title: "Maintenance and troubleshooting",
    summary:
      "Keeping a machine accurate over years, and finding faults by evidence instead of by guesswork.",
    tier: "practice",
    lessonSlugs: [],
    requires: [13, 18],
    topics: [
      "Preventive, predictive and reactive maintenance compared",
      "Lubrication schedules and why they get skipped",
      "Way covers, seals and contamination control",
      "Condition monitoring: vibration, temperature, current signature",
      "Backlash and lost-motion checks over time",
      "Reading alarm histories and control diagnostics",
      "Structured fault-finding: symptom, hypothesis, cheapest decisive test",
      "Surface finish and dimensional symptoms as diagnostic evidence",
      "Spare parts strategy and downtime cost",
      "Recording what you changed, and why it matters",
    ],
    status: "planned",
  },
  {
    number: 20,
    slug: "complete-cnc-design-project",
    title: "Complete CNC design project",
    summary:
      "Put every level together: work through twenty design decisions and produce your own machine concept report.",
    tier: "practice",
    lessonSlugs: ["selecting-an-architecture"],
    requires: [1, 2, 4, 13],
    topics: [
      "Writing a design brief from an intended use",
      "Workpiece envelope, material and required travels",
      "Choosing an architecture against the brief",
      "Estimating cutting forces and spindle requirements",
      "Structure, material and stiffness targets",
      "Guideway and axis drive selection",
      "Motor and drive estimates",
      "Electrical and control architecture",
      "Auxiliary systems and chip management",
      "Safety concept from the start, not bolted on",
      "Manufacturing, assembly and alignment strategy",
      "Validation plan and acceptance criteria",
      "Maintenance plan and serviceability",
      "Risk register and honest trade-off statements",
      "Producing a concept report for engineering review",
    ],
    status: "published",
  },
];

/** Levels in the order they appear on the roadmap, grouped by tier. */
export const TIER_ORDER: LevelTier[] = ["foundation", "mechanical", "control", "practice"];

export function levelsByTier(tier: LevelTier): Level[] {
  return curriculum.filter((l) => l.tier === tier).sort((a, b) => a.number - b.number);
}

export function getLevel(numberOrSlug: number | string): Level | undefined {
  return typeof numberOrSlug === "number"
    ? curriculum.find((l) => l.number === numberOrSlug)
    : curriculum.find((l) => l.slug === numberOrSlug);
}

/** Every published lesson slug, in teaching order across the whole course. */
export const teachingOrder: string[] = [
  "what-is-a-cnc-machine",
  "cad-to-finished-component",
  "understanding-xyz",
  "how-a-ball-screw-moves-an-axis",
  "accuracy-repeatability-resolution",
  "intro-to-machine-architecture",
  "selecting-an-architecture",
];

export const TOTAL_LEVELS = curriculum.length;
